import { mockStorage } from '@/lib/storage/mock-storage';

/**
 * Customer-facing notification feed (storefront). Persisted through mockStorage so
 * notifications generated by an admin status change survive a refresh and remain
 * readable on the tracking page. Distinct from `data/mock/notifications.ts`, which
 * is the internal admin feed.
 */
export interface CustomerNotification {
  id: string;
  orderId: string;
  orderNumber: string;
  status: string;
  title: string;
  message: string;
  date: string;
  isRead: boolean;
}

export let mockCustomerNotifications: CustomerNotification[] = [];

mockCustomerNotifications = mockStorage.read('customer_notifications', mockCustomerNotifications);

export const updateMockCustomerNotifications = (data: CustomerNotification[]) => {
  mockCustomerNotifications = data;
  mockStorage.write('customer_notifications', data);
};
